swagger: '2.0'
info:
  title: City Car Management API
  version: "1.0"
paths:
  /:
    get:
      summary: Welcome message
      responses:
        200:
          description: Welcome message
  /owners:
    post:
      summary: Add a car owner
      parameters:
        - name: owner
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        201:
          description: Owner created
        400:
          description: Validation error
    get:
      summary: Get all owners
      responses:
        200:
          description: List of owners
  /cars:
    post:
      summary: Add a car
      parameters:
        - name: car
          in: body
          required: true
          schema:
            type: object
            properties:
              color:
                type: string
                enum: [yellow, blue, gray]
              model:
                type: string
                enum: [hatch, sedan, convertible]
              owner_id:
                type: integer
      responses:
        201:
          description: Car created
        400:
          description: Validation error
        404:
          description: Owner not found
    get:
      summary: Get all cars
      responses:
        200:
          description: List of cars
  /owners/sales_opportunities:
    get:
      summary: Get owners with sales opportunities
      responses:
        200:
          description: List of owners with sales opportunities
